---

# **<span style="color:yellow">Part A</span>** - Environment Setup

### **1.** What is a **Library**

>A **Library** is a collection of pre-written code that helps us to perform tasks without writing everything from scratch.

For this lab, the important libraries are: 

| Library          | Main purpose                                   |
| ---------------- | ---------------------------------------------- |
| **NumPy**        | Numerical calculations and arrays              |
| **Pandas**       | Working with datasets and tables               |
| **Scikit-learn** | Machine Learning tools, datasets, models, etc. |

### **2.** Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import sklearn

### **3.** Why do we use `as np` and `as pd`?

>`as np` and `as pd` create short names called aliases, for the libraries. This makes the library easier and faster to refer to when writing code.

---

# **<span style="color:yellow">Part B<span>** - Working with the Iris Dataset

### **1.** Load the Iris dataset

In [3]:
# First import the dataset then load it

from sklearn.datasets import load_iris

iris = load_iris()

`load_iris()` is a built-in function in Scikit-learn.

The Iris dataset contains 150 flower samples from 3 different species.

### **2.** Print the number of rows and columns

In [4]:
print("Number of rows: ", iris.data.shape[0])

print("Number of columns: ", iris.data.shape[1])

Number of rows:  150
Number of columns:  4

* **150** = number of rows / samples / instances

* **4** = number of features / attributes / columns

### **3.** Print feature names

In [5]:
print("Feature Names: ")
print(iris.feature_names)

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

### **4.** Print target names

In [6]:
print("Target Names: ")
print(iris.target_names)

Target Names:
['setosa' 'versicolor' 'virginica']

### **5.** Convert the dataset into a Pandas DataFrame

In [7]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Displaying it
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

>At this point, the DataFrame contains only the features.

Now let's add the target column.

In [8]:
df["target"] = iris.target

# Displaying it
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

### **6.** Add the actual flower species names

The target values are numbers:

<center>

0

1

2

</center>

We can convert them into species names:

In [9]:
df["species"] = iris.target_names[iris.target]

# To display 1st 5 rows of the dataset
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

### **7.** Identify Dataset, Instance, Attribute and Label

#### **i. Dataset**

> The complete collection of data.
>
> Here it is the Iris dataset containing information about 150 iris flowers.

### **ii. Instance**

> One individual data record or row.
>
> For example: df.iloc[0] -- This represents one flower.

#### **iii. Attribute / Feature**

>The input characteristics used to describe a data instance.
>
>In the Iris dataset:
>
>sepal length
>sepal width
>petal length
>petal width

#### **iv. Label / Target**

>The value we want to predict.
>
>In this dataset:species 
>
> or 
> 
> its numerical representation: target

### **8.** Why is understanding the dataset important before applying a Machine Learning algorithm?

>Understanding the dataset helps us identify the features, target variable, data types, missing values, data distribution and possible data quality problems. This helps us select appropriate preprocessing methods and machine learning algorithms.

---

# **<span style="color:yellow">Part C<span>** - Dataset Exploration

Now we will explore the DataFrame.

### **1.** Display the shape

In [10]:
df.shape

(150, 6)

### **2.** Display column names

In [11]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target', 'species'],
      dtype='str')

### **3.** Display data types

In [13]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
species                  str
dtype: object

### **4.** Display the first few rows

In [14]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

You can also specify the number:

In [15]:
df.head(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
5,5.4,3.9,1.7,0.4,0,setosa
6,4.6,3.4,1.4,0.3,0,setosa
7,5.0,3.4,1.5,0.2,0,setosa
8,4.4,2.9,1.4,0.2,0,setosa
9,4.9,3.1,1.5,0.1,0,setosa

### **5.** Display the last few rows

In [16]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

For the last 10 rows:

In [17]:
df.tail(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
140,6.7,3.1,5.6,2.4,2,virginica
141,6.9,3.1,5.1,2.3,2,virginica
142,5.8,2.7,5.1,1.9,2,virginica
143,6.8,3.2,5.9,2.3,2,virginica
144,6.7,3.3,5.7,2.5,2,virginica
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

### **6.** Display dataset information

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
 5   species            150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 8.4 KB

>This helps us to see:
>
> * Number of entries
> * Column names
> * Non-null values
> * Data types
> * Memory usage

### **7.** Get statistical information

In [19]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

>This gives statistics such as:
>
> * count
> * mean
> * standard deviation
> * minimum
> * 25% (Q1)
> * 50% (Q2)
> * 75% (Q3)
> * maximum

### **8.** Find the feature with the highest average value

First, calculate the mean:

In [20]:
df[iris.feature_names].mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

To directly find the feature with the highest mean:

In [21]:
df[iris.feature_names].mean().idxmax()

'sepal length (cm)'

To see both the feature and its value:

In [23]:
highest_average = df[iris.feature_names].mean().idxmax()

print("Feature with the hightest Average: ", highest_average)
print("Average Value: ", df[highest_average].mean())

Feature with the hightest Average:  sepal length (cm)
Average Value:  5.843333333333334

### **9.** Find the feature with the largest variation

Variation here refers to the **standard deviation**.

In [24]:
df[iris.feature_names].std()

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

To find the feature with the largest standard deviation:

In [25]:
df[iris.feature_names].std().idxmax()

'petal length (cm)'

### **10.** Find the feature with the smallest minimum value

In [26]:
df[iris.feature_names].min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

To directly find the feature:

In [27]:
df[iris.feature_names].min().idxmin()

'petal width (cm)'

### **11.** Display value counts for the target column

In [28]:
df["target"].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

You can also check the species names:

In [29]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

### **12.** Is the Iris dataset balanced?

A dataset is **balanced** when each class has approximately the same number of instances.

Check:

In [30]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

>Answer
>
>Yes, the Iris dataset is balanced because each of the three classes contains 50 instances.

### **13.** Why is checking class distribution important?

> Checking class distribution is important because an imbalanced dataset can cause a machine learning model to become biased toward the majority class. Accuracy alone can also become misleading when the classes are highly imbalanced.

---

# **<span style="color:yellow">Part D</span>** - Understanding Machine Learning Concepts

### **1.** Types of Data

> **i.** Structured data
>
> **ii.** Semi-structured data
>
> **iii.** Unstructured data

### Identify each example

| Example                                | Data Type       | Why?                                                           |
| -------------------------------------- | --------------- | -------------------------------------------------------------- |
| Customer database in MySQL             | Structured      | Data is organized into rows and columns                        |
| JSON from REST API                     | Semi-structured | Has tags/keys but does not follow a fixed table structure      |
| CCTV surveillance video                | Unstructured    | Does not have a predefined tabular format                      |
| Emails with headers and message bodies | Semi-structured | Headers have structure but message content can be unstructured |
| Excel spreadsheet with student marks   | Structured      | Organized into rows and columns                                |

### Which type is easiest for traditional ML?

> Structured data

### Why?

> Structured data is already organized into rows and columns, making it easier to use as input for traditional machine learning algorithms.

### Why is unstructured data more challenging?

> Unstructured data does not follow a predefined format. Therefore, additional processing and feature extraction are usually required before it can be used effectively by machine learning algorithms.
>
> **Examples:**
> Images, Videos, Audio, Free text

### **2.** Identify the Learning Paradigm

| Scenario                                                    | Learning Paradigm          |
| ----------------------------------------------------------- | -------------------------- |
| Predicting loan default using labelled historical data      | **Supervised Learning**    |
| Grouping customers without predefined labels                | **Unsupervised Learning**  |
| Robot learning using rewards and penalties                  | **Reinforcement Learning** |
| Predicting house prices using historical data               | **Supervised Learning**    |
| Detecting unusual transactions without labelled fraud cases | **Unsupervised Learning**  |

---

<center>

# ***<u><span style="color:#2ECC71">Important Points***</span></u>

</center>

<div align="right">

#### <span style="color:lightgreen">**Supervised Learning**</span>

The dataset has input features and known labels/targets.

***Examples:*** Spam detection, House price prediction, Loan default prediction

</div>

<div align="center">

#### <span style="color:lightgreen">**Unsupervised Learning**</span>

The dataset does not have predefined labels.

The algorithm tries to find patterns or groups.

***Examples:*** Customer segmentation

</div>

<div align="left">

#### <span style="color:lightgreen">**Reinforcement Learning**</span>

An agent learns through:

&emsp;&emsp; • Actions

&emsp;&emsp; • Rewards

&emsp;&emsp; • Penalties

***Example:*** A robot learning to navigate a maze

</div>

---

### **3.** Underfitting, Good Fit and Overfitting

You are given:

| Model | Training Accuracy | Testing Accuracy |
| ----- | ----------------: | ---------------: |
| A     |               99% |              61% |
| B     |               90% |              88% |
| C     |               58% |              55% |

##### **Model A** - Overfitting

**Why?** The training accuracy is very high, but the testing accuracy is much lower.

<div align=center>

```python
Training: 99%
Testing:  61%
```

</div>

* The model learned the training data too specifically and cannot generalize well to unseen data.

##### **Model B** - Good Fit

<div align=center>

```python
Training: 90%
Testing:  88%
```

</div>

* Both accuracies are high and close to each other.

* This means the model generalizes reasonably well.

##### **Model C** - Underfitting

<div align=center>

```python
Training: 58%
Testing:  55%
```

</div>

* Both accuracies are low.

* This means the model has not learned the patterns in the data sufficiently.

- - -

<div align=center style="color:lightblue">

#### <u>**Main disadvantage of overfitting**</u>
</div>

An overfitted model performs very well on the training data but poorly on new or unseen data.

<div align=center style="color:lightpink">

#### <u>**Techniques to reduce overfitting**</u>
</div>

* Cross-validation
* Regularization
* Reducing model complexity
* Feature selection
* Early stopping
* Using more training data

<U> **In Simple:** </u> Regularization can help reduce overfitting by preventing the model from becoming too complex.


- - -

### **4.** Training, Validation and Testing Sets

<div align="left">

#### <span style="color:lightgreen">**Training Set**</span>

***Used to:*** Train the machine learning model and learn patterns from the data.

</div>

<div align="center">

#### <span style="color:lightgreen">**Validation Set**</span>

***Used to:*** Tune the model and select the best hyperparameters during development.

</div>

<div align="right">

#### <span style="color:lightgreen">**Testing Set**</span>

***Used to:*** Evaluate the final performance of the model using unseen data.

</div>

#### **●** Why use a separate test dataset?

> A separate test dataset provides an unbiased evaluation of how well the model can generalize to unseen data.

#### **●** A student trains and evaluates a model using the same dataset and gets 99% accuracy. Does this mean the model performs well?

>No.
>
>The model may have memorized or overfitted the training data. High accuracy on the same dataset does not guarantee good performance on unseen data. A separate test dataset is required to evaluate the model's ability to generalize.